/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Controlers.CtrlUser;
import Entities.User;
import Tools.ConnexionBDD;
import java.awt.event.KeyEvent;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author jacqu
 */
public class FrmConnexion extends javax.swing.JFrame {

    ConnexionBDD maCnx;
    private CtrlUser ctrlUser;

    public FrmConnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        lblIdentifiant = new javax.swing.JLabel();
        lblMdp = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        btnConnexion = new javax.swing.JButton();
        txtMdp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Se connecter");

        lblIdentifiant.setText("Identifiant");

        lblMdp.setText("Mot de passe");

        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
        });

        btnConnexion.setText("Se connecter");
        btnConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnexionActionPerformed(evt);
            }
        });
        btnConnexion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConnexionKeyPressed(evt);
            }
        });

        txtMdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMdpKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdentifiant)
                            .addComponent(lblMdp))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(lblTitre)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentifiant)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMdp)
                    .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        maCnx = new ConnexionBDD();
        ctrlUser = new CtrlUser();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_formWindowOpened

    private void btnConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnexionActionPerformed
        try {
            connexion();
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(FrmConnexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConnexionActionPerformed

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                connexion();
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(FrmConnexion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void txtMdpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMdpKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                connexion();
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(FrmConnexion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtMdpKeyPressed

    private void btnConnexionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConnexionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                connexion();
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(FrmConnexion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnConnexionKeyPressed

    private void connexion() throws NoSuchAlgorithmException {
        String login = txtLogin.getText();
        String mdp = ctrlUser.md5(txtMdp.getText());
        
        
        if(login.compareTo("") == 0) {
            txtLogin.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez saisir un identifiant", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else if(mdp.compareTo("") == 0) {
            txtMdp.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez saisir un mot de passe ", "Erreur", JOptionPane.WARNING_MESSAGE);
        } 
        else {
            User leUser = ctrlUser.GetConnexionEleve(login, mdp);
            if (leUser == null){
                leUser = ctrlUser.GetConnexionMoniteur(login, mdp);
                if (leUser == null) {
                    leUser = ctrlUser.GetConnexionResponsable(login, mdp);
                    if (leUser == null) {
                        JOptionPane.showMessageDialog(this, "Identifiant ou mot de passe incorrect", "Erreur", JOptionPane.WARNING_MESSAGE);
                    }
                    else { //Reponsable
                        FrmInterfaceResponsable frm = new FrmInterfaceResponsable(leUser);
                        this.setVisible(false);
                        frm.setVisible(true);
                    }
                }
                else { //Moniteur
                    FrmInterfacePrincipale frm = new FrmInterfacePrincipale(leUser);
                    this.setVisible(false);
                    frm.setVisible(true);
                }
            }
            else { //Eleve
                FrmInterfacePrincipale frm = new FrmInterfacePrincipale(leUser);
                this.setVisible(false);
                frm.setVisible(true);
            }
        }
    }
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnexion;
    private javax.swing.JLabel lblIdentifiant;
    private javax.swing.JLabel lblMdp;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtMdp;
    // End of variables declaration//GEN-END:variables
}
