/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlPlanning;
import Entities.Planning;
import Entities.User;
import Tools.ConnexionBDD;
import Tools.ModelJTable;
import java.awt.Image;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author nicol
 */
public class FrmInterfacePrincipale extends javax.swing.JFrame {

    static User unUser;
    private CtrlPlanning ctrlPlanning;
    ModelJTable mdl;
    
    /**
     * Creates new form FrmInterfacePrincipaleMoniteur
     */
    public FrmInterfacePrincipale(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStatistique = new javax.swing.JButton();
        btnModifierMesInfos = new javax.swing.JButton();
        btnLeconLicence = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPlanning = new javax.swing.JTable();
        lblTitre = new javax.swing.JLabel();
        lblSeDeconnecter = new javax.swing.JLabel();
        lblLogoDeconnexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnStatistique.setText("Statistiques");
        btnStatistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistiqueActionPerformed(evt);
            }
        });

        btnModifierMesInfos.setText("Modifier mes infos");
        btnModifierMesInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierMesInfosActionPerformed(evt);
            }
        });

        btnLeconLicence.setText("Lecon / Licence");
        btnLeconLicence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeconLicenceActionPerformed(evt);
            }
        });

        tblPlanning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPlanning);

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Bienvenue");

        lblSeDeconnecter.setForeground(new java.awt.Color(0, 51, 255));
        lblSeDeconnecter.setText("Se déconnecter");
        lblSeDeconnecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSeDeconnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSeDeconnecterMouseClicked(evt);
            }
        });

        lblLogoDeconnexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoDeconnexion.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoDeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoDeconnexionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnStatistique, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifierMesInfos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLeconLicence, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSeDeconnecter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogoDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeDeconnecter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogoDeconnexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnModifierMesInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLeconLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStatistique, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStatistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistiqueActionPerformed
        if (unUser.getStatut() == 0) {
            FrmStatistiquesEleve frm = new FrmStatistiquesEleve(unUser);
            this.setVisible(false);
            frm.setVisible(true);
        }
        else {
            FrmStatistiquesMoniteur frm = new FrmStatistiquesMoniteur(unUser);
            this.setVisible(false);
            frm.setVisible(true);
        }
    }//GEN-LAST:event_btnStatistiqueActionPerformed

    private void btnModifierMesInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierMesInfosActionPerformed
        FrmModifierInfos frm = new FrmModifierInfos(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnModifierMesInfosActionPerformed

    private void btnLeconLicenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeconLicenceActionPerformed
        if (unUser.getStatut() == 0) {
            FrmReserverLecon frm = new FrmReserverLecon(unUser);
            this.setVisible(false);
            frm.setVisible(true);
        }
        else {
            FrmAjouterLicence frm = new FrmAjouterLicence(unUser);
            this.setVisible(false);
            frm.setVisible(true);
        }
    }//GEN-LAST:event_btnLeconLicenceActionPerformed

    private void lblSeDeconnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeDeconnecterMouseClicked
        seDeconnecter();
    }//GEN-LAST:event_lblSeDeconnecterMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        lblTitre.setText("Bienvenue " + unUser.getPrenom());
        ctrlPlanning = new CtrlPlanning();
        
        if (unUser.getStatut() == 0) {
            btnLeconLicence.setText("Reserver une leçon");
            mdl = new ModelJTable();
            mdl.LoadDataPlanning(ctrlPlanning.GetPlanningByEleveId(unUser.getCodeUser()));
            tblPlanning.setModel(mdl);
        }
        else {
            btnLeconLicence.setText("Ajouter une licence");
            mdl = new ModelJTable();
            mdl.LoadDataPlanning(ctrlPlanning.GetPlanningByMoniteurId(unUser.getCodeUser()));
            tblPlanning.setModel(mdl);
        }
        
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/deconnexion.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(lblLogoDeconnexion.getWidth(), lblLogoDeconnexion.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        lblLogoDeconnexion.setIcon(ic);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        seDeconnecter();
    }//GEN-LAST:event_formWindowClosing

    private void lblLogoDeconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoDeconnexionMouseClicked
        seDeconnecter();
    }//GEN-LAST:event_lblLogoDeconnexionMouseClicked

    private void seDeconnecter() {
        unUser = null;
        FrmConnexion frm = new FrmConnexion();
        this.setVisible(false);
        frm.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInterfacePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInterfacePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInterfacePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInterfacePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInterfacePrincipale(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeconLicence;
    private javax.swing.JButton btnModifierMesInfos;
    private javax.swing.JButton btnStatistique;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogoDeconnexion;
    private javax.swing.JLabel lblSeDeconnecter;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTable tblPlanning;
    // End of variables declaration//GEN-END:variables
}
