/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlGraphique;
import Entities.ChiffreAffaireParCategorie;
import Entities.User;
import static Vues.FrmInterfacePrincipale.unUser;
import java.awt.BorderLayout;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author nicol
 */
public class FrmInterfaceResponsable extends javax.swing.JFrame {

    static User unUser;
    SimpleDateFormat sdf;
    CtrlGraphique ctrlGraphique;
    /**
     * Creates new form FrmInterfaceResponsable
     */
    public FrmInterfaceResponsable(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        btnAjouterCategorie = new javax.swing.JButton();
        lblSeDeconnecter = new javax.swing.JLabel();
        lblLogoDeconnexion = new javax.swing.JLabel();
        btnModifierVehicule = new javax.swing.JButton();
        btnAjouterVehicule1 = new javax.swing.JButton();
        btnModifierCategorie = new javax.swing.JButton();
        btnAjouterMoniteur = new javax.swing.JButton();
        btnAjouterEleve = new javax.swing.JButton();
        btnVisualiserPlanning = new javax.swing.JButton();
        btnModifierMesInfos = new javax.swing.JButton();
        dcFin = new com.toedter.calendar.JDateChooser();
        dcDebut = new com.toedter.calendar.JDateChooser();
        pnlGraphique = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Bienvenue");

        btnAjouterCategorie.setText("Ajouter une catégorie");
        btnAjouterCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCategorieActionPerformed(evt);
            }
        });

        lblSeDeconnecter.setForeground(new java.awt.Color(0, 51, 255));
        lblSeDeconnecter.setText("Se déconnecter");
        lblSeDeconnecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSeDeconnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSeDeconnecterMouseClicked(evt);
            }
        });

        lblLogoDeconnexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoDeconnexion.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoDeconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoDeconnexionMouseClicked(evt);
            }
        });

        btnModifierVehicule.setText("Modifier un véhicule");
        btnModifierVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierVehiculeActionPerformed(evt);
            }
        });

        btnAjouterVehicule1.setText("Ajouter un véhicule");
        btnAjouterVehicule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterVehicule1ActionPerformed(evt);
            }
        });

        btnModifierCategorie.setText("Modifier une catégorie");
        btnModifierCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierCategorieActionPerformed(evt);
            }
        });

        btnAjouterMoniteur.setText("Ajouter un moniteur");
        btnAjouterMoniteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterMoniteurActionPerformed(evt);
            }
        });

        btnAjouterEleve.setText("Ajouter un élève");
        btnAjouterEleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterEleveActionPerformed(evt);
            }
        });

        btnVisualiserPlanning.setText("Visualiser un planning");
        btnVisualiserPlanning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualiserPlanningActionPerformed(evt);
            }
        });

        btnModifierMesInfos.setText("Modifier mes infos");
        btnModifierMesInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierMesInfosActionPerformed(evt);
            }
        });

        pnlGraphique.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlGraphique.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 659, Short.MAX_VALUE)
                        .addComponent(lblSeDeconnecter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogoDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dcDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dcFin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlGraphique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnModifierVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnModifierCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(btnAjouterCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAjouterVehicule1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAjouterMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAjouterEleve, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnVisualiserPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnModifierMesInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeDeconnecter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogoDeconnexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAjouterCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAjouterVehicule1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnModifierVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModifierCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAjouterMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAjouterEleve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnVisualiserPlanning, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModifierMesInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(pnlGraphique, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCategorieActionPerformed
        FrmAjouterCategorie frm = new FrmAjouterCategorie(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnAjouterCategorieActionPerformed

    private void lblSeDeconnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSeDeconnecterMouseClicked
        seDeconnecter();
    }//GEN-LAST:event_lblSeDeconnecterMouseClicked

    private void lblLogoDeconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoDeconnexionMouseClicked
        seDeconnecter();
    }//GEN-LAST:event_lblLogoDeconnexionMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        seDeconnecter();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlGraphique = new CtrlGraphique();
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        lblTitre.setText("Bienvenue " + unUser.getPrenom());
        
        dcDebut.setDateFormatString("dd/MM/yyyy");
        dcFin.setDateFormatString("dd/MM/yyyy");
        java.util.Date date = new java.util.Date();
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.DATE, -7);
        dcDebut.setDate(calendar.getTime());
        dcFin.setDate(date);
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/deconnexion.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(lblLogoDeconnexion.getWidth(), lblLogoDeconnexion.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        lblLogoDeconnexion.setIcon(ic);
        
        
        actualiserAffichage();
        
        dcDebut.getDateEditor().addPropertyChangeListener(
        e -> {
            actualiserAffichage();
        });
        
        dcFin.getDateEditor().addPropertyChangeListener(
        e -> {
            actualiserAffichage();
        });
    }//GEN-LAST:event_formWindowOpened

    private void btnModifierVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierVehiculeActionPerformed
        FrmModifierVehicule frm = new FrmModifierVehicule(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnModifierVehiculeActionPerformed

    private void btnAjouterVehicule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterVehicule1ActionPerformed
        FrmAjouterVehicule frm = new FrmAjouterVehicule(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnAjouterVehicule1ActionPerformed

    private void btnModifierCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierCategorieActionPerformed
        FrmModifierCategorie frm = new FrmModifierCategorie(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnModifierCategorieActionPerformed

    private void btnAjouterMoniteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterMoniteurActionPerformed
        FrmAjouterMoniteur frm = new FrmAjouterMoniteur(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnAjouterMoniteurActionPerformed

    private void btnAjouterEleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterEleveActionPerformed
        FrmAjouterEleve frm = new FrmAjouterEleve(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnAjouterEleveActionPerformed

    private void btnVisualiserPlanningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualiserPlanningActionPerformed
        FrmVisualiserPlanning frm = new FrmVisualiserPlanning(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnVisualiserPlanningActionPerformed

    private void btnModifierMesInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierMesInfosActionPerformed
        FrmModifierInfos frm = new FrmModifierInfos(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_btnModifierMesInfosActionPerformed

    private void actualiserAffichage() {
        if (dcDebut.getDate() != null && dcFin.getDate() != null) {
            sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = sdf.format(dcDebut.getDate());
            String date2 = sdf.format(dcFin.getDate());
            
            DefaultCategoryDataset donnees = new DefaultCategoryDataset();
            ArrayList<ChiffreAffaireParCategorie> lesValeurs = new ArrayList<>();
            lesValeurs = ctrlGraphique.GetDatasGraphiqueResponsable(date1, date2);
            for (ChiffreAffaireParCategorie uneValeur : lesValeurs) {
                donnees.setValue( uneValeur.getChiffreAffaire(), "", uneValeur.getLibelleCategorie());
            }
            JFreeChart chart1 = ChartFactory.createBarChart(
                      "Chiffre d'affaires par catégorie",
             "Nom de la catégorie",
               "Chiffre d'affaires",
                    donnees,
                 PlotOrientation.VERTICAL, false, true, false);
            ChartPanel graph = new ChartPanel(chart1);
            pnlGraphique.removeAll();
            pnlGraphique.add(graph, BorderLayout.CENTER);
            pnlGraphique.validate();
        }
    }
    
    
    private void seDeconnecter() {
        unUser = null;
        FrmConnexion frm = new FrmConnexion();
        this.setVisible(false);
        frm.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInterfaceResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInterfaceResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInterfaceResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInterfaceResponsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInterfaceResponsable(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterCategorie;
    private javax.swing.JButton btnAjouterEleve;
    private javax.swing.JButton btnAjouterMoniteur;
    private javax.swing.JButton btnAjouterVehicule1;
    private javax.swing.JButton btnModifierCategorie;
    private javax.swing.JButton btnModifierMesInfos;
    private javax.swing.JButton btnModifierVehicule;
    private javax.swing.JButton btnVisualiserPlanning;
    private com.toedter.calendar.JDateChooser dcDebut;
    private com.toedter.calendar.JDateChooser dcFin;
    private javax.swing.JLabel lblLogoDeconnexion;
    private javax.swing.JLabel lblSeDeconnecter;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JPanel pnlGraphique;
    // End of variables declaration//GEN-END:variables
}
