/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlCategorie;
import Controlers.CtrlLicence;
import Controlers.CtrlVehicule;
import Entities.Categorie;
import Entities.User;
import Tools.ModelJTable;
import static Vues.FrmInterfacePrincipale.unUser;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Poste de travail
 */
public class FrmModifierCategorie extends javax.swing.JFrame {

    static User unUser;
    private CtrlCategorie ctrlCategorie;
    private ModelJTable mdl;
    private ArrayList<Categorie> toutesLesCategories = new ArrayList<>();
    
    /**
     * Creates new form FrmAjouterLicence
     */
    public FrmModifierCategorie(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLibelle = new javax.swing.JLabel();
        lblPrix = new javax.swing.JLabel();
        lblTitre = new javax.swing.JLabel();
        lblRetour = new javax.swing.JLabel();
        lblEnregistrer = new javax.swing.JLabel();
        lblLogoValider = new javax.swing.JLabel();
        lblLogoRetour = new javax.swing.JLabel();
        txtLibelle = new javax.swing.JTextField();
        sprPrix = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategories = new javax.swing.JTable();
        txtRecherche = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblLibelle.setText("Libellé");

        lblPrix.setText("Prix (en euro)");

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Modifier une catégorie");

        lblRetour.setForeground(new java.awt.Color(0, 51, 255));
        lblRetour.setText("Retour");
        lblRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetourMouseClicked(evt);
            }
        });

        lblEnregistrer.setForeground(new java.awt.Color(0, 51, 255));
        lblEnregistrer.setText("Enregistrer");
        lblEnregistrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEnregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnregistrerMouseClicked(evt);
            }
        });

        lblLogoValider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoValider.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoValiderMouseClicked(evt);
            }
        });

        lblLogoRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoRetour.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoRetourMouseClicked(evt);
            }
        });

        tblCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblCategoriesMouseReleased(evt);
            }
        });
        tblCategories.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCategoriesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblCategories);

        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitre)
                .addGap(280, 280, 280))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRetour)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrix)
                            .addComponent(lblLibelle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLibelle)
                            .addComponent(sprPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogoValider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRecherche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLibelle)
                                    .addComponent(txtLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrix)
                                    .addComponent(sprPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRetour)
                            .addComponent(lblEnregistrer)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogoValider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlCategorie = new CtrlCategorie();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
      
        SpinnerModel spinnerModel = new SpinnerNumberModel(30.00, 0, 1000, 0.01);
        sprPrix.setModel(spinnerModel);
        
        toutesLesCategories = ctrlCategorie.GetToutesLesCategories();
        
        MaJTable();
        txtLibelle.requestFocusInWindow();
        
        
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/enregistrer.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(lblLogoValider.getWidth(), lblLogoValider.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        lblLogoValider.setIcon(ic);
        
        icon = new ImageIcon(getClass().getResource("/Images/retour.png"));
        img = icon.getImage();
        img = img.getScaledInstance(lblLogoRetour.getWidth(), lblLogoRetour.getHeight(), Image.SCALE_SMOOTH);
        ic = new ImageIcon(img);
        lblLogoRetour.setIcon(ic);
    }//GEN-LAST:event_formWindowOpened

    private void lblRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblRetourMouseClicked

    private void lblEnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnregistrerMouseClicked
        validerEnregistrerCategorie();
    }//GEN-LAST:event_lblEnregistrerMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        retour();
    }//GEN-LAST:event_formWindowClosing

    private void lblLogoRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblLogoRetourMouseClicked

    private void lblLogoValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoValiderMouseClicked
        validerEnregistrerCategorie();
    }//GEN-LAST:event_lblLogoValiderMouseClicked

    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
        MaJTable();
    }//GEN-LAST:event_txtRechercheKeyReleased

    private void tblCategoriesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriesMouseReleased
        afficherInfoCategorie();
    }//GEN-LAST:event_tblCategoriesMouseReleased

    private void tblCategoriesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCategoriesKeyReleased
        afficherInfoCategorie();
    }//GEN-LAST:event_tblCategoriesKeyReleased
    
    public void MaJTable() {
        mdl = new ModelJTable();
        mdl.LoadDataCategorie(toutesLesCategories, txtRecherche.getText());
        tblCategories.setModel(mdl);
        if (tblCategories.getRowCount() != 0) {
            tblCategories.setRowSelectionInterval(0, 0);
            afficherInfoCategorie();
        }
    }
    
    public void afficherInfoCategorie() {
        txtLibelle.setText(tblCategories.getValueAt(tblCategories.getSelectedRow(), 0).toString());
        sprPrix.setValue(Double.parseDouble(tblCategories.getValueAt(tblCategories.getSelectedRow(), 1).toString()));
    }
    
    public void validerEnregistrerCategorie() {
        if (txtLibelle.getText().equals("")) {
            txtLibelle.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez écrire le libellé de la catégorie", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else {
            ctrlCategorie.ModifierCategorie(tblCategories.getValueAt(tblCategories.getSelectedRow(), 0).toString(), txtLibelle.getText(), Double.parseDouble(sprPrix.getValue().toString()));
            JOptionPane.showMessageDialog(this, "La catégorie a bien été modifiée", "Modifiée", JOptionPane.INFORMATION_MESSAGE);
            retour();
        }
    }
    
    private void retour() {
        FrmInterfaceResponsable frm = new FrmInterfaceResponsable(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModifierCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModifierCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModifierCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModifierCategorie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModifierCategorie(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnregistrer;
    private javax.swing.JLabel lblLibelle;
    private javax.swing.JLabel lblLogoRetour;
    private javax.swing.JLabel lblLogoValider;
    private javax.swing.JLabel lblPrix;
    private javax.swing.JLabel lblRetour;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JSpinner sprPrix;
    private javax.swing.JTable tblCategories;
    private javax.swing.JTextField txtLibelle;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
