/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlUser;
import Entities.User;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class FrmModifierInfos extends javax.swing.JFrame {

    
    static User unUser;
    CtrlUser ctrlUser;
    SimpleDateFormat sdf;
    
    /**
     * Creates new form FrmModifierInfos
     */
    public FrmModifierInfos(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitre = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblSexe = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        lblDateNaissance = new javax.swing.JLabel();
        lblTelephone = new javax.swing.JLabel();
        lblCodePostal = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        lblVille = new javax.swing.JLabel();
        lblEnregistrer = new javax.swing.JLabel();
        lblRetour = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtCodePostal = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        rbHomme = new javax.swing.JRadioButton();
        rbFemme = new javax.swing.JRadioButton();
        dcDateNaissance = new com.toedter.calendar.JDateChooser();
        lblLogoEnregistrer = new javax.swing.JLabel();
        lblLogoRetour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Modifier mes informations");

        lblNom.setText("Nom");

        lblSexe.setText("Sexe");

        lblPrenom.setText("Prénom");

        lblDateNaissance.setText("Date de naissance");

        lblTelephone.setText("Téléphone");

        lblCodePostal.setText("Code postal");

        lblAdresse.setText("Adresse");

        lblVille.setText("Ville");

        lblEnregistrer.setForeground(new java.awt.Color(0, 51, 255));
        lblEnregistrer.setText("Enregistrer");
        lblEnregistrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEnregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnregistrerMouseClicked(evt);
            }
        });

        lblRetour.setForeground(new java.awt.Color(0, 51, 255));
        lblRetour.setText("Retour");
        lblRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetourMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbHomme);
        rbHomme.setText("Homme");

        buttonGroup1.add(rbFemme);
        rbFemme.setText("Femme");

        lblLogoEnregistrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoEnregistrer.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoEnregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoEnregistrerMouseClicked(evt);
            }
        });

        lblLogoRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoRetour.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoRetourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(lblAdresse))
                        .addComponent(lblTelephone)
                        .addComponent(lblSexe))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRetour)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbHomme)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbFemme)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(dcDateNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEnregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogoEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDateNaissance)
                    .addComponent(lblPrenom)
                    .addComponent(lblCodePostal)
                    .addComponent(lblVille))
                .addGap(32, 32, 32)
                .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(lblPrenom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexe)
                            .addComponent(lblDateNaissance)
                            .addComponent(rbHomme)
                            .addComponent(rbFemme)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(dcDateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelephone)
                    .addComponent(lblCodePostal)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdresse)
                            .addComponent(lblVille)
                            .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRetour)
                            .addComponent(lblEnregistrer)))
                    .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogoEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dcDateNaissance.setDateFormatString("dd/MM/yyyy");
        ctrlUser = new CtrlUser();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        sdf = new SimpleDateFormat("yyyy-MM-dd");
        
        txtNom.setText(unUser.getNom());
        txtPrenom.setText(unUser.getPrenom());
        txtCodePostal.setText(unUser.getCodePostal());
        txtTelephone.setText(unUser.getTelephone());
        txtAdresse.setText(unUser.getAdresse());
        txtVille.setText(unUser.getVille());
        try {
            if (unUser.getDateDeNaissance() != "") {
                dcDateNaissance.setDate(sdf.parse(unUser.getDateDeNaissance()));
            }
        } catch (ParseException ex) {
            Logger.getLogger(FrmModifierInfos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (unUser.getSexe() == 0) {
            rbHomme.setSelected(true);
        }
        else {
            rbFemme.setSelected(true);
        }
        
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/enregistrer.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(lblLogoEnregistrer.getWidth(), lblLogoEnregistrer.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        lblLogoEnregistrer.setIcon(ic);
        
        icon = new ImageIcon(getClass().getResource("/Images/retour.png"));
        img = icon.getImage();
        img = img.getScaledInstance(lblLogoRetour.getWidth(), lblLogoRetour.getHeight(), Image.SCALE_SMOOTH);
        ic = new ImageIcon(img);
        lblLogoRetour.setIcon(ic);
    }//GEN-LAST:event_formWindowOpened

    private void lblEnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnregistrerMouseClicked
        enregistrerModif();
    }//GEN-LAST:event_lblEnregistrerMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        retour();
    }//GEN-LAST:event_formWindowClosing

    private void lblRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblRetourMouseClicked

    private void lblLogoRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblLogoRetourMouseClicked

    private void lblLogoEnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoEnregistrerMouseClicked
        enregistrerModif();
    }//GEN-LAST:event_lblLogoEnregistrerMouseClicked

    private void enregistrerModif() {
        if (txtNom.getText().equals("")) {
            txtNom.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez saisir votre nom", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else if (txtPrenom.getText().equals("")){
            txtPrenom.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez saisir votre prénom", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else if (txtTelephone.getText().equals("")){
            txtTelephone.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez saisir votre numéro de téléphone", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else {
            unUser.setNom(txtNom.getText());
            unUser.setPrenom(txtPrenom.getText());
            int sexe = 0;
            if (rbFemme.isSelected()) {
                sexe = 1;
            }
            unUser.setSexe(sexe);
            unUser.setDateDeNaissance(null);
            if (dcDateNaissance.getDate() != null) {
               unUser.setDateDeNaissance(sdf.format(dcDateNaissance.getDate())); 
            }
            unUser.setAdresse(txtAdresse.getText());
            unUser.setCodePostal(txtCodePostal.getText());
            unUser.setVille(txtVille.getText());
            unUser.setTelephone(txtTelephone.getText());

            ctrlUser.MaJInfos(unUser);

            JOptionPane.showMessageDialog(this, "Votre profil a bien été mis à jour", "Enregistré", JOptionPane.INFORMATION_MESSAGE);
            retour();
        }
    }
    
    
    private void retour() {
        if (unUser.getStatut() == 2) {
            FrmInterfaceResponsable frm = new FrmInterfaceResponsable(unUser);
            this.setVisible(false);
            frm.setVisible(true);
        }
        else {
            FrmInterfacePrincipale frm = new FrmInterfacePrincipale(unUser);
            this.setVisible(false);
            frm.setVisible(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModifierInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModifierInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModifierInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModifierInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModifierInfos(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dcDateNaissance;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblCodePostal;
    private javax.swing.JLabel lblDateNaissance;
    private javax.swing.JLabel lblEnregistrer;
    private javax.swing.JLabel lblLogoEnregistrer;
    private javax.swing.JLabel lblLogoRetour;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JLabel lblRetour;
    private javax.swing.JLabel lblSexe;
    private javax.swing.JLabel lblTelephone;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JLabel lblVille;
    private javax.swing.JRadioButton rbFemme;
    private javax.swing.JRadioButton rbHomme;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtCodePostal;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
