/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlCategorie;
import Controlers.CtrlLicence;
import Controlers.CtrlVehicule;
import Entities.Categorie;
import Entities.User;
import Entities.Vehicule;
import Tools.ModelJTable;
import static Vues.FrmInterfacePrincipale.unUser;
import java.awt.Image;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Poste de travail
 */
public class FrmModifierVehicule extends javax.swing.JFrame {

    static User unUser;
    private CtrlCategorie ctrlCategorie;
    private CtrlVehicule ctrlVehicule;
    private CtrlLicence ctrlLicence;
    ModelJTable mdl;
    private ArrayList<Vehicule> tousLesVehicules = new ArrayList<>();
    
    /**
     * Creates new form FrmAjouterLicence
     */
    public FrmModifierVehicule(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        lblRetour = new javax.swing.JLabel();
        lblEnregistrer = new javax.swing.JLabel();
        lblLogoValider = new javax.swing.JLabel();
        lblLogoRetour = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehicules = new javax.swing.JTable();
        txtRecherche = new javax.swing.JTextField();
        lblMarque = new javax.swing.JLabel();
        txtMarque = new javax.swing.JTextField();
        lblModele = new javax.swing.JLabel();
        txtModele = new javax.swing.JTextField();
        lblCategorie = new javax.swing.JLabel();
        cboCategorie = new javax.swing.JComboBox<>();
        lblImmatriculation = new javax.swing.JLabel();
        lblAnnee = new javax.swing.JLabel();
        txtImmatriculation = new javax.swing.JTextField();
        sprAnnee = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Modifier un véhicule");

        lblRetour.setForeground(new java.awt.Color(0, 51, 255));
        lblRetour.setText("Retour");
        lblRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetourMouseClicked(evt);
            }
        });

        lblEnregistrer.setForeground(new java.awt.Color(0, 51, 255));
        lblEnregistrer.setText("Enregistrer");
        lblEnregistrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEnregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnregistrerMouseClicked(evt);
            }
        });

        lblLogoValider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoValider.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoValiderMouseClicked(evt);
            }
        });

        lblLogoRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoRetour.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoRetourMouseClicked(evt);
            }
        });

        tblVehicules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblVehicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblVehiculesMouseReleased(evt);
            }
        });
        tblVehicules.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblVehiculesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblVehicules);

        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });

        lblMarque.setText("Marque");

        lblModele.setText("Modèle");

        lblCategorie.setText("Catégorie");

        lblImmatriculation.setText("Immatriculation");

        lblAnnee.setText("Année");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRetour))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCategorie)
                            .addComponent(lblAnnee)
                            .addComponent(lblImmatriculation)
                            .addComponent(lblMarque)
                            .addComponent(lblModele))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtModele)
                            .addComponent(txtMarque, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtImmatriculation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sprAnnee, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogoValider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRecherche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(lblTitre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRetour)
                                    .addComponent(lblEnregistrer)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblImmatriculation)
                                    .addComponent(txtImmatriculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMarque)
                                    .addComponent(txtMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModele)
                                    .addComponent(txtModele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAnnee)
                                    .addComponent(sprAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCategorie)
                                    .addComponent(cboCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLogoValider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlVehicule = new CtrlVehicule();
        ctrlCategorie = new CtrlCategorie();
        ctrlLicence = new CtrlLicence();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
     
        LocalDate dte = LocalDate.now();
        SpinnerModel spinnerModel = new SpinnerNumberModel(dte.getYear(), 1900, dte.getYear(), 1);
        sprAnnee.setModel(spinnerModel);
        
        ArrayList<Categorie> lesCategories = new ArrayList<>();
        lesCategories = ctrlCategorie.GetToutesLesCategories();
        ctrlCategorie.InitialiserCboCategories(cboCategorie, lesCategories);
        
        tousLesVehicules = ctrlVehicule.GetTousLesVehicules();
        
        MaJTable();
        txtImmatriculation.requestFocusInWindow();
       
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/enregistrer.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(lblLogoValider.getWidth(), lblLogoValider.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        lblLogoValider.setIcon(ic);
        
        icon = new ImageIcon(getClass().getResource("/Images/retour.png"));
        img = icon.getImage();
        img = img.getScaledInstance(lblLogoRetour.getWidth(), lblLogoRetour.getHeight(), Image.SCALE_SMOOTH);
        ic = new ImageIcon(img);
        lblLogoRetour.setIcon(ic);
    }//GEN-LAST:event_formWindowOpened

    private void lblRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblRetourMouseClicked

    private void lblEnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnregistrerMouseClicked
        validerEnregistrerCategorie();
    }//GEN-LAST:event_lblEnregistrerMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        retour();
    }//GEN-LAST:event_formWindowClosing

    private void lblLogoRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblLogoRetourMouseClicked

    private void lblLogoValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoValiderMouseClicked
        validerEnregistrerCategorie();
    }//GEN-LAST:event_lblLogoValiderMouseClicked

    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
        MaJTable();
    }//GEN-LAST:event_txtRechercheKeyReleased

    private void tblVehiculesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVehiculesMouseReleased
        afficherInfoVehicule();
    }//GEN-LAST:event_tblVehiculesMouseReleased

    private void tblVehiculesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblVehiculesKeyReleased
        afficherInfoVehicule();
    }//GEN-LAST:event_tblVehiculesKeyReleased
    
    public void MaJTable() {
        mdl = new ModelJTable();
        mdl.LoadDataVehicule(tousLesVehicules, txtRecherche.getText());
        tblVehicules.setModel(mdl);
        if (tblVehicules.getRowCount() != 0) {
            tblVehicules.setRowSelectionInterval(0, 0);
            afficherInfoVehicule();
        }
    }
    
    public void afficherInfoVehicule() {
        txtImmatriculation.setText(tblVehicules.getValueAt(tblVehicules.getSelectedRow(), 0).toString());
        txtMarque.setText(tblVehicules.getValueAt(tblVehicules.getSelectedRow(), 1).toString());
        txtModele.setText(tblVehicules.getValueAt(tblVehicules.getSelectedRow(), 2).toString());
        sprAnnee.setValue(Integer.parseInt(tblVehicules.getValueAt(tblVehicules.getSelectedRow(), 3).toString()));
        cboCategorie.setSelectedItem(tblVehicules.getValueAt(tblVehicules.getSelectedRow(), 4).toString());
    }
    
    public void validerEnregistrerCategorie() {
        if (txtImmatriculation.getText().equals("")) {
            txtImmatriculation.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez écrire l'immatriculation", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else if (txtMarque.getText().equals("")) {
            txtMarque.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez écrire la marque", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else if (txtModele.getText().equals("")) {
            txtModele.requestFocusInWindow();
            JOptionPane.showMessageDialog(this, "Veuillez écrire le modèle", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else {
            int leCodeCategorie = ctrlLicence.GetIdCategorieByName(cboCategorie.getSelectedItem().toString());
            ctrlVehicule.ModifierVehicule(tblVehicules.getValueAt(tblVehicules.getSelectedRow(), 0).toString(), txtImmatriculation.getText(), txtMarque.getText(), txtModele.getText(), Integer.parseInt(sprAnnee.getValue().toString()), leCodeCategorie);
            JOptionPane.showMessageDialog(this, "Le véhicule a bien été modifié", "Modifié", JOptionPane.INFORMATION_MESSAGE);
            retour();
        }
    }
    
    private void retour() {
        FrmInterfaceResponsable frm = new FrmInterfaceResponsable(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModifierVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModifierVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModifierVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModifierVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModifierVehicule(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCategorie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnnee;
    private javax.swing.JLabel lblCategorie;
    private javax.swing.JLabel lblEnregistrer;
    private javax.swing.JLabel lblImmatriculation;
    private javax.swing.JLabel lblLogoRetour;
    private javax.swing.JLabel lblLogoValider;
    private javax.swing.JLabel lblMarque;
    private javax.swing.JLabel lblModele;
    private javax.swing.JLabel lblRetour;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JSpinner sprAnnee;
    private javax.swing.JTable tblVehicules;
    private javax.swing.JTextField txtImmatriculation;
    private javax.swing.JTextField txtMarque;
    private javax.swing.JTextField txtModele;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
