/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlCategorie;
import Controlers.CtrlLecon;
import Controlers.CtrlLicence;
import Controlers.CtrlVehicule;
import Controlers.CtrlMoniteur;
import Entities.Categorie;
import Entities.Moniteur;
import Entities.User;
import Entities.Vehicule;
import Tools.ConnexionBDD;
import static Vues.FrmModifierInfos.unUser;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Poste de travail
 */
public class FrmReserverLecon extends javax.swing.JFrame {

    
    static User unUser;
    private CtrlVehicule ctrlVehicule;
    private CtrlCategorie ctrlCategorie;
    private CtrlLicence ctrlLicence;
    private CtrlMoniteur ctrlMoniteur;
    private CtrlLecon ctrlLecon;
    SimpleDateFormat sdf;
    
    private ArrayList<String> listeImmatriculation;
    private ArrayList<Integer> listeCodeMoniteurs;
    
    /**
     * Creates new form FrmReserverLeçon
     */
    public FrmReserverLecon(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        lblHeures = new javax.swing.JLabel();
        lblCatV = new javax.swing.JLabel();
        cboHeures = new javax.swing.JComboBox<>();
        cboCategorieVehicule = new javax.swing.JComboBox<>();
        lblMoniteurs = new javax.swing.JLabel();
        cboMoniteurs = new javax.swing.JComboBox<>();
        lblVehicules = new javax.swing.JLabel();
        cboVehicules = new javax.swing.JComboBox<>();
        dcDateLecon = new com.toedter.calendar.JDateChooser();
        lblTitre = new javax.swing.JLabel();
        lblReserver = new javax.swing.JLabel();
        lblRetour = new javax.swing.JLabel();
        lblLogoValider = new javax.swing.JLabel();
        lblLogoRetour = new javax.swing.JLabel();

        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblDate.setText("Date");

        lblHeures.setText("Heures disponibles");

        lblCatV.setText("Type de véhicule");

        cboHeures.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHeuresItemStateChanged(evt);
            }
        });

        cboCategorieVehicule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCategorieVehiculeItemStateChanged(evt);
            }
        });

        lblMoniteurs.setText("Moniteurs disponibles");

        lblVehicules.setText("Véhicules disponibles");

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Réserver une licence");

        lblReserver.setForeground(new java.awt.Color(0, 51, 255));
        lblReserver.setText("Réserver");
        lblReserver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReserver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReserverMouseClicked(evt);
            }
        });

        lblRetour.setForeground(new java.awt.Color(0, 51, 255));
        lblRetour.setText("Retour");
        lblRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetourMouseClicked(evt);
            }
        });

        lblLogoValider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoValider.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoValiderMouseClicked(evt);
            }
        });

        lblLogoRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoRetour.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoRetourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRetour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReserver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLogoValider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDate)
                                    .addComponent(lblCatV)
                                    .addComponent(lblHeures)
                                    .addComponent(lblMoniteurs)
                                    .addComponent(lblVehicules))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cboMoniteurs, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboCategorieVehicule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboHeures, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dcDateLecon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(cboVehicules, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(lblTitre)))
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReserver)
                            .addComponent(lblRetour)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDate)
                            .addComponent(dcDateLecon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeures)
                            .addComponent(cboHeures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCatV)
                            .addComponent(cboCategorieVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMoniteurs)
                            .addComponent(cboMoniteurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicules)
                            .addComponent(cboVehicules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogoValider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlVehicule = new CtrlVehicule();
        ctrlCategorie = new CtrlCategorie();
        ctrlMoniteur = new CtrlMoniteur();
        ctrlLecon = new CtrlLecon();
        ctrlLicence = new CtrlLicence();
        sdf = new SimpleDateFormat("yyyy-MM-dd");
        listeCodeMoniteurs = new ArrayList<>();
        listeImmatriculation = new ArrayList<>();
        
        dcDateLecon.setDateFormatString("dd/MM/yyyy");
        java.util.Date date = new java.util.Date();
        dcDateLecon.setDate(date);
        
        ArrayList<Categorie> lesCategories = new ArrayList<>();
        lesCategories = ctrlCategorie.GetToutesLesCategories();
        ctrlCategorie.InitialiserCboCategories(cboCategorieVehicule, lesCategories);
        
        ctrlLecon.InitialiserCboHeure(cboHeures);
         
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/valider.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(lblLogoValider.getWidth(), lblLogoValider.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        lblLogoValider.setIcon(ic);
        icon = new ImageIcon(getClass().getResource("/Images/retour.png"));
        img = icon.getImage();
        img = img.getScaledInstance(lblLogoRetour.getWidth(), lblLogoRetour.getHeight(), Image.SCALE_SMOOTH);
        ic = new ImageIcon(img);
        lblLogoRetour.setIcon(ic);
        
        
        actualiserMoniteurVehicule();
                
        dcDateLecon.getDateEditor().addPropertyChangeListener(
        e -> {
            actualiserMoniteurVehicule();
        });
    }//GEN-LAST:event_formWindowOpened

    private void cboCategorieVehiculeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCategorieVehiculeItemStateChanged
        actualiserMoniteurVehicule();
    }//GEN-LAST:event_cboCategorieVehiculeItemStateChanged

    private void lblReserverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReserverMouseClicked
        reserver();
    }//GEN-LAST:event_lblReserverMouseClicked

    private void lblRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblRetourMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        retour();
    }//GEN-LAST:event_formWindowClosing

    private void cboHeuresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHeuresItemStateChanged
        actualiserMoniteurVehicule();
    }//GEN-LAST:event_cboHeuresItemStateChanged

    private void lblLogoValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoValiderMouseClicked
        reserver();
    }//GEN-LAST:event_lblLogoValiderMouseClicked

    private void lblLogoRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblLogoRetourMouseClicked

    public void reserver() {
        if (cboMoniteurs.getSelectedItem().toString() == "Aucun moniteur" || cboMoniteurs.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez choisir un moniteur", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else if (cboVehicules.getSelectedItem().toString() == "Aucun véhicule" || cboVehicules.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez choisir un véhicule", "Erreur", JOptionPane.WARNING_MESSAGE);
        }
        else {
            String date = sdf.format(dcDateLecon.getDate());
            String heure = String.valueOf(cboHeures.getSelectedItem());
            int codeCategorie = ctrlLicence.GetIdCategorieByName(cboCategorieVehicule.getSelectedItem().toString());
            int codeMoniteur = listeCodeMoniteurs.get(cboMoniteurs.getSelectedIndex());
            String immatriculation = listeImmatriculation.get(cboVehicules.getSelectedIndex());
            
            ctrlLecon.AjouterLecon(date, heure, codeMoniteur, unUser.getCodeUser(), immatriculation);
            JOptionPane.showMessageDialog(this, "Votre réservation a bien été prise en compte", "Réservé", JOptionPane.INFORMATION_MESSAGE);
            retour();
        }
    }
    
    
    private void retour() {
        FrmInterfacePrincipale frm = new FrmInterfacePrincipale(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }
    
    
    private void actualiserMoniteurVehicule() {
        String date = sdf.format(dcDateLecon.getDate());
        String heure = String.valueOf(cboHeures.getSelectedItem());
        int codeCategorie = ctrlLicence.GetIdCategorieByName(cboCategorieVehicule.getSelectedItem().toString());
        
        ArrayList<Moniteur> lesMoniteurs = new ArrayList<>();
        lesMoniteurs = ctrlMoniteur.GetMoniteursDispo(date, heure, codeCategorie);
        ctrlMoniteur.InitialiserCboMoniteurDispo(cboMoniteurs, lesMoniteurs);
        listeCodeMoniteurs.clear();
        listeCodeMoniteurs = ctrlMoniteur.LoadMoniteurCode(lesMoniteurs);
        
        ArrayList<Vehicule> lesVehicules = new ArrayList<>();
        lesVehicules = ctrlVehicule.GetVehiculeDispo(date, heure, codeCategorie);
        ctrlVehicule.InitialiserCboVehiculeDispo(cboVehicules, lesVehicules);
        listeImmatriculation.clear();
        listeImmatriculation = ctrlVehicule.LoadImmatriculation(lesVehicules);
    }
            
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReserverLecon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReserverLecon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReserverLecon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReserverLecon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReserverLecon(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCategorieVehicule;
    private javax.swing.JComboBox<String> cboHeures;
    private javax.swing.JComboBox<String> cboMoniteurs;
    private javax.swing.JComboBox<String> cboVehicules;
    private com.toedter.calendar.JDateChooser dcDateLecon;
    private javax.swing.JLabel lblCatV;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHeures;
    private javax.swing.JLabel lblLogoRetour;
    private javax.swing.JLabel lblLogoValider;
    private javax.swing.JLabel lblMoniteurs;
    private javax.swing.JLabel lblReserver;
    private javax.swing.JLabel lblRetour;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JLabel lblVehicules;
    // End of variables declaration//GEN-END:variables
}
