/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlLecon;
import Entities.User;
import Tools.ConnexionBDD;
import static Vues.FrmModifierInfos.unUser;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Poste de travail
 */
public class FrmStatistiquesEleve extends javax.swing.JFrame {

    private CtrlLecon ctrlLecon;
    static User unUser;
    /*private CtrlVehicule ctrlV;
    private CtrlMoniteur ctrlM;
    private CtrlPlanning ctrlP;*/
    
    /**
     * Creates new form FrmStatistiques
     */
    public FrmStatistiquesEleve(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNbLecons = new javax.swing.JLabel();
        txtNbLecons = new javax.swing.JTextField();
        txtLeconsFinies = new javax.swing.JTextField();
        lblLeconsFinies = new javax.swing.JLabel();
        lblLeconsFutures = new javax.swing.JLabel();
        txtLeconsFutures = new javax.swing.JTextField();
        lblMontantTotal = new javax.swing.JLabel();
        txtMontantTotal = new javax.swing.JTextField();
        lblMontantPasRegle = new javax.swing.JLabel();
        txtMontantPasRegle = new javax.swing.JTextField();
        txtMontantRegle = new javax.swing.JTextField();
        lblMontantRegle = new javax.swing.JLabel();
        lblTitre = new javax.swing.JLabel();
        lblRetour = new javax.swing.JLabel();
        lblLogoRetour = new javax.swing.JLabel();

        setTitle("Auto NMN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNbLecons.setText("Total de leçons");

        lblLeconsFinies.setText("Leçons déjà effectuées");

        lblLeconsFutures.setText("Leçons à faire");

        lblMontantTotal.setText("Montant total");

        lblMontantPasRegle.setText("Montant à régler");

        lblMontantRegle.setText("Montant déjà réglé");

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Statistiques");

        lblRetour.setForeground(new java.awt.Color(0, 51, 255));
        lblRetour.setText("Retour");
        lblRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetourMouseClicked(evt);
            }
        });

        lblLogoRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoRetour.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoRetourMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitre)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNbLecons)
                            .addComponent(lblLeconsFinies)
                            .addComponent(lblLeconsFutures)
                            .addComponent(lblMontantTotal)
                            .addComponent(lblMontantPasRegle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRetour)
                                .addGap(71, 71, 71))
                            .addComponent(lblMontantRegle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLeconsFinies, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNbLecons, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLeconsFutures, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantPasRegle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontantRegle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbLecons)
                    .addComponent(txtNbLecons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLeconsFinies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLeconsFinies))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLeconsFutures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLeconsFutures))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMontantTotal)
                            .addComponent(txtMontantTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMontantPasRegle)
                            .addComponent(txtMontantPasRegle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMontantRegle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMontantRegle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(lblRetour))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        ctrlLecon = new CtrlLecon();
        
        txtNbLecons.setEditable(false);
        txtLeconsFinies.setEditable(false);
        txtLeconsFutures.setEditable(false);
        txtMontantTotal.setEditable(false);
        txtMontantPasRegle.setEditable(false);
        txtMontantRegle.setEditable(false);
        
        int LeconsTerminees = ctrlLecon.GetNbLeconsTerminees(unUser.getCodeUser());
        int LeconsNonFaites = ctrlLecon.GetNbLeconsNonFaites(unUser.getCodeUser());
        double PrixRestantAPayer = ctrlLecon.GetPrixRestantAPayer(unUser.getCodeUser());
        double PrixPaye = ctrlLecon.GetPrixPaye(unUser.getCodeUser());
        
        txtNbLecons.setText(String.valueOf(LeconsTerminees + LeconsNonFaites));
        txtLeconsFinies.setText(String.valueOf(LeconsTerminees));
        txtLeconsFutures.setText(String.valueOf(LeconsNonFaites));
        txtMontantTotal.setText(String.valueOf(PrixRestantAPayer + PrixPaye)+" €");
        txtMontantPasRegle.setText(String.valueOf(PrixRestantAPayer)+" €");
        txtMontantRegle.setText(String.valueOf(PrixPaye)+" €");
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/retour.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(lblLogoRetour.getWidth(), lblLogoRetour.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        lblLogoRetour.setIcon(ic);
    }//GEN-LAST:event_formWindowOpened

    private void lblRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblRetourMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        retour();
    }//GEN-LAST:event_formWindowClosing

    private void lblLogoRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblLogoRetourMouseClicked

    private void retour() {
        FrmInterfacePrincipale frm = new FrmInterfacePrincipale(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmStatistiquesEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmStatistiquesEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmStatistiquesEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmStatistiquesEleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStatistiquesEleve(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLeconsFinies;
    private javax.swing.JLabel lblLeconsFutures;
    private javax.swing.JLabel lblLogoRetour;
    private javax.swing.JLabel lblMontantPasRegle;
    private javax.swing.JLabel lblMontantRegle;
    private javax.swing.JLabel lblMontantTotal;
    private javax.swing.JLabel lblNbLecons;
    private javax.swing.JLabel lblRetour;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTextField txtLeconsFinies;
    private javax.swing.JTextField txtLeconsFutures;
    private javax.swing.JTextField txtMontantPasRegle;
    private javax.swing.JTextField txtMontantRegle;
    private javax.swing.JTextField txtMontantTotal;
    private javax.swing.JTextField txtNbLecons;
    // End of variables declaration//GEN-END:variables
}
