/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Controlers.CtrlMoniteur;
import Controlers.CtrlUser;
import Controlers.CtrlPlanning;
import Entities.Moniteur;
import Entities.User;
import Tools.ModelJTable;
import static Vues.FrmInterfaceResponsable.unUser;
import static Vues.FrmStatistiquesEleve.unUser;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author maxdb
 */
public class FrmVisualiserPlanning extends javax.swing.JFrame {
    static User unUser;
    private CtrlMoniteur ctrlMoniteur;
    private CtrlUser ctrlUser;
    private CtrlPlanning ctrlPlanning;
    ModelJTable mdl;
    private ArrayList<User> tousLesUsers = new ArrayList<>();
    private ArrayList<Moniteur> tousLesMoniteurs = new ArrayList<>();
    /**
     * Creates new form FrmVisualiserPlanning
     */
    public FrmVisualiserPlanning(User unUser) {
        this.unUser = unUser;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CboTypeUser = new javax.swing.JComboBox<>();
        txtInfo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecherche = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlanning = new javax.swing.JTable();
        lblRetour = new javax.swing.JLabel();
        lblLogoRetour = new javax.swing.JLabel();
        lblTitre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        CboTypeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elève", "Moniteur" }));
        CboTypeUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CboTypeUserItemStateChanged(evt);
            }
        });

        txtInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInfoKeyReleased(evt);
            }
        });

        tblRecherche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblRechercheMouseReleased(evt);
            }
        });
        tblRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblRechercheKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblRecherche);

        tblPlanning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblPlanning);

        lblRetour.setForeground(new java.awt.Color(0, 51, 255));
        lblRetour.setText("Retour");
        lblRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRetourMouseClicked(evt);
            }
        });

        lblLogoRetour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogoRetour.setPreferredSize(new java.awt.Dimension(25, 25));
        lblLogoRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoRetourMouseClicked(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Visualiser un planning");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRetour))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CboTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lblTitre)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CboTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogoRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRetour))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblRetourMouseClicked

    private void lblLogoRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoRetourMouseClicked
        retour();
    }//GEN-LAST:event_lblLogoRetourMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        retour();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ctrlMoniteur = new CtrlMoniteur();
        ctrlUser = new CtrlUser();
        ctrlPlanning = new CtrlPlanning();
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/retour.png"));
        Image img = icon.getImage();
        img = img.getScaledInstance(lblLogoRetour.getWidth(), lblLogoRetour.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(img);
        lblLogoRetour.setIcon(ic);
        
        tousLesMoniteurs = ctrlMoniteur.GetTousLesMoniteurs();
        tousLesUsers = ctrlUser.GetTousLesUsers();
        
        MaJTable();
        
    }//GEN-LAST:event_formWindowOpened

    private void CboTypeUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CboTypeUserItemStateChanged
        MaJTable();
    }//GEN-LAST:event_CboTypeUserItemStateChanged

    private void txtInfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInfoKeyReleased
        MaJTable();
    }//GEN-LAST:event_txtInfoKeyReleased

    private void tblRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblRechercheKeyReleased
        AfficherPlanning();
    }//GEN-LAST:event_tblRechercheKeyReleased

    private void tblRechercheMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRechercheMouseReleased
        AfficherPlanning();
    }//GEN-LAST:event_tblRechercheMouseReleased
//    public void MaJTableMoniteur() {
//        mdl = new ModelJTable();
//        mdl.LoadDataMoniteur(tousLesMoniteurs, txtInfo.getText());
//        tblRecherche.setModel(mdl);
//        if (tblRecherche.getRowCount() != 0) {
//            tblRecherche.setRowSelectionInterval(0, 0);
//            AfficherPlanning();
//        }
//    }
//    
//    public void MaJTableUser() {
//        mdl = new ModelJTable();
//        mdl.LoadDataUser(tousLesUsers, txtInfo.getText());
//        tblRecherche.setModel(mdl);
//        if (tblRecherche.getRowCount() != 0) {
//            tblRecherche.setRowSelectionInterval(0, 0);
//            AfficherPlanning();
//        }
//    }
    
    public void MaJTable() {
        mdl = new ModelJTable();
        if("Elève".equals(CboTypeUser.getSelectedItem().toString())){
            mdl.LoadDataUser(tousLesUsers, txtInfo.getText());
            tblRecherche.setModel(mdl);
        }
        else if("Moniteur".equals(CboTypeUser.getSelectedItem().toString())){
            mdl.LoadDataMoniteur(tousLesMoniteurs, txtInfo.getText());
            tblRecherche.setModel(mdl);
        }
        if (tblRecherche.getRowCount() != 0) {
            tblRecherche.setRowSelectionInterval(0, 0);
            AfficherPlanning();
        }
    }
        
    public void AfficherPlanning() {
        mdl = new ModelJTable();
        if("Elève".equals(CboTypeUser.getSelectedItem().toString())){
            int idUser = Integer.parseInt(tblRecherche.getValueAt(tblRecherche.getSelectedRow(), 0).toString());
            mdl.LoadDataPlanning(ctrlPlanning.GetPlanningByEleveId(idUser));
        }
        else if("Moniteur".equals(CboTypeUser.getSelectedItem().toString())){
            int idMoniteur = Integer.parseInt(tblRecherche.getValueAt(tblRecherche.getSelectedRow(), 0).toString());
            mdl.LoadDataPlanning(ctrlPlanning.GetPlanningByMoniteurId(idMoniteur));
        }
        tblPlanning.setModel(mdl);
    }
    
    private void retour() {
        FrmInterfaceResponsable frm = new FrmInterfaceResponsable(unUser);
        this.setVisible(false);
        frm.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisualiserPlanning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisualiserPlanning(unUser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboTypeUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLogoRetour;
    private javax.swing.JLabel lblRetour;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTable tblPlanning;
    private javax.swing.JTable tblRecherche;
    private javax.swing.JTextField txtInfo;
    // End of variables declaration//GEN-END:variables
}
